attribute = "#b39df3"
comment = "#7f8490"
constant = "#b39df3"
"constant.character.escape" = "#f39660"
"constant.numeric" = "#b39df3"
constructor = "#76cce0"
"diff.delta" = "#f39660"
"diff.minus" = "#fc5d7c"
"diff.plus" = "#9ed072"
function = "#9ed072"
"function.builtin" = "#76cce0"
"function.macro" = "#b39df3"
keyword = "#fc5d7c"
label = "#f39660"
"markup.heading.marker" = "#7f8490"
"markup.link.text" = "#b39df3"
"markup.list" = "#fc5d7c"
"markup.quote" = "#7f8490"
"markup.raw" = "#9ed072"
module = "#76cce0"
namespace = "#76cce0"
operator = "#f39660"
punctuation = "#7f8490"
"punctuation.bracket" = "#e2e2e3"
"punctuation.delimiter" = "#7f8490"
special = "#f39660"
string = "#e7c664"
tag = "#e7c664"
type = "#76cce0"
"ui.linenr" = "#7f8490"
"ui.linenr.selected" = "#e2e2e3"
"ui.text" = "#e2e2e3"
"ui.text.focus" = "#9ed072"
variable = "#e2e2e3"
"variable.builtin" = "#f39660"
"variable.other.member" = "#e2e2e3"
"variable.parameter" = "#e2e2e3"

["diagnostic.error".underline]
color = "#fc5d7c"
style = "curl"

["diagnostic.hint".underline]
color = "#76cce0"
style = "curl"

["diagnostic.info".underline]
color = "#9ed072"
style = "curl"

["diagnostic.warning".underline]
color = "#e7c664"
style = "curl"

[error]
bg = "#363944"
fg = "#fc5d7c"
modifiers = ["bold"]

[hint]
bg = "#363944"
fg = "#76cce0"
modifiers = ["bold"]

[info]
bg = "#363944"
fg = "#9ed072"

["markup.bold"]
modifiers = ["bold"]

["markup.heading.1"]
fg = "#fc5d7c"
modifiers = ["bold"]

["markup.heading.2"]
fg = "#f39660"
modifiers = ["bold"]

["markup.heading.3"]
fg = "#e7c664"
modifiers = ["bold"]

["markup.heading.4"]
fg = "#9ed072"
modifiers = ["bold"]

["markup.heading.5"]
fg = "#76cce0"
modifiers = ["bold"]

["markup.heading.6"]
fg = "#e2e2e3"
modifiers = ["bold"]

["markup.italic"]
modifiers = ["italic"]

["markup.link.url"]
fg = "#76cce0"
modifiers = ["underlined"]

["markup.strikethrough"]
modifiers = ["crossed_out"]

["ui.background"]
bg = "#2c2e34"

["ui.cursor"]
modifiers = ["reversed"]

["ui.cursor.insert"]
bg = "#7f8490"
fg = "#181819"

["ui.cursor.match"]
bg = "#4e432f"
fg = "#f39660"

["ui.cursor.select"]
bg = "#76cce0"
fg = "#2c2e34"

["ui.cursorline.primary"]
bg = "#33353f"

["ui.help"]
bg = "#33353f"
fg = "#e2e2e3"

["ui.menu"]
bg = "#363944"
fg = "#e2e2e3"

["ui.menu.selected"]
bg = "#9ed072"
fg = "#2c2e34"

["ui.popup"]
bg = "#363944"
fg = "#7f8490"

["ui.selection"]
bg = "#444852"

["ui.selection.primary"]
bg = "#5C606A"

["ui.statusline"]
bg = "#3b3e48"
fg = "#e2e2e3"

["ui.statusline.inactive"]
bg = "#33353f"
fg = "#7f8490"

["ui.statusline.insert"]
bg = "#9ed072"
fg = "#2c2e34"
modifiers = ["bold"]

["ui.statusline.normal"]
bg = "#76cce0"
fg = "#2c2e34"
modifiers = ["bold"]

["ui.statusline.select"]
bg = "#b39df3"
fg = "#2c2e34"
modifiers = ["bold"]

["ui.virtual.inlay-hint"]
fg = "#595f6f"

["ui.virtual.ruler"]
bg = "#3b3e48"

["ui.virtual.whitespace"]
fg = "#595f6f"

["ui.window"]
bg = "#2c2e34"
fg = "#7f8490"

[warning]
bg = "#363944"
fg = "#e7c664"
modifiers = ["bold"]
