theme = "onedark"
[editor]
bufferline = "multiple"
completion-trigger-len = 1
cursorline = true
idle-timeout = 100
line-number = "relative"
rulers = [200]
true-color = true
[editor.auto-pairs]
"(" = ")"
"<" = ">"
"[" = "]"
"`" = "`"
"{" = "}"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "┆"
render = true

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
center = ["file-name", "file-modification-indicator"]
left = ["mode", "spinner", "diagnostics", "version-control"]
right = ["file-type", "file-encoding", "position"]

[editor.whitespace.render]
newline = "none"
space = "all"
tab = "all"

[keys]
[keys.insert]
down = "no_op"
end = "no_op"
home = "no_op"
left = "no_op"
pagedown = "no_op"
pageup = "no_op"
right = "no_op"
up = "no_op"

[keys.normal]
S-backspace = "file_picker"
backspace = "file_picker_in_current_directory"
down = "no_op"
end = "no_op"
home = "no_op"
left = "no_op"
pagedown = "no_op"
pageup = "no_op"
right = "no_op"
up = "no_op"
